/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.List;
import java.awt.event.ActionListener;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTabbedPane;
import javax.swing.JTextField;

/**
 *
 * @author rannypa
 */
public class MenuAdmin extends javax.swing.JFrame {

    /**
     * Creates new form MenuAdmin
     */
    public MenuAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TPAdmin = new javax.swing.JTabbedPane();
        PTambahLokasi = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TFtambahnamalokasi = new javax.swing.JTextField();
        TFnomorLokasi = new javax.swing.JTextField();
        BSimpanLokasi = new javax.swing.JButton();
        PHapusLokasi = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TFnomorlokasihapus = new javax.swing.JTextField();
        BHapusLokasi = new javax.swing.JButton();
        PTambahKelompok = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TFIdKelompoktambahklp = new javax.swing.JTextField();
        BSimpanKelompok = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListLokasi = new javax.swing.JList<>();
        jLabel22 = new javax.swing.JLabel();
        jTFUrutanL = new javax.swing.JTextField();
        PHapusKelompok = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        BHapusKelompok = new javax.swing.JButton();
        LLokasiKlphapuskelompok = new java.awt.List();
        TFIdKlphapuskelompok = new javax.swing.JTextField();
        PHapusPembimbing = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        LpilihPembimbing = new java.awt.List();
        BHapusPembimbing = new javax.swing.JButton();
        PTambahPembimbing = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        TFNamadpnpembimbing = new javax.swing.JTextField();
        TFNamablkPembimbing = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        RBLakipembimbing = new javax.swing.JRadioButton();
        RBPerempuanpembimbing = new javax.swing.JRadioButton();
        CBTahunpembimbing = new javax.swing.JComboBox<>();
        CBBulanpembimbing = new javax.swing.JComboBox<>();
        CBTanggalpembimbing = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        TFTeleponpembimbing = new javax.swing.JTextField();
        TFAlamatpembimbing = new javax.swing.JTextField();
        TFnippembimbing = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        BSimpan2 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("TAMBAH LOKASI");

        jLabel2.setText("Nama Lokasi");

        jLabel3.setText("Nomor Lokasi ");

        BSimpanLokasi.setText("Simpan");

        javax.swing.GroupLayout PTambahLokasiLayout = new javax.swing.GroupLayout(PTambahLokasi);
        PTambahLokasi.setLayout(PTambahLokasiLayout);
        PTambahLokasiLayout.setHorizontalGroup(
            PTambahLokasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PTambahLokasiLayout.createSequentialGroup()
                .addGroup(PTambahLokasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PTambahLokasiLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1))
                    .addGroup(PTambahLokasiLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(PTambahLokasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(PTambahLokasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TFtambahnamalokasi, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                            .addComponent(TFnomorLokasi))))
                .addContainerGap(244, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PTambahLokasiLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BSimpanLokasi)
                .addGap(57, 57, 57))
        );
        PTambahLokasiLayout.setVerticalGroup(
            PTambahLokasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PTambahLokasiLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(PTambahLokasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TFtambahnamalokasi, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PTambahLokasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TFnomorLokasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addComponent(BSimpanLokasi)
                .addContainerGap(135, Short.MAX_VALUE))
        );

        TPAdmin.addTab("Tambah Lokasi", PTambahLokasi);

        jLabel4.setText("HAPUS LOKASI");

        jLabel5.setText("Masukan Nomor Lokasi");

        BHapusLokasi.setText("Hapus");

        javax.swing.GroupLayout PHapusLokasiLayout = new javax.swing.GroupLayout(PHapusLokasi);
        PHapusLokasi.setLayout(PHapusLokasiLayout);
        PHapusLokasiLayout.setHorizontalGroup(
            PHapusLokasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PHapusLokasiLayout.createSequentialGroup()
                .addGroup(PHapusLokasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PHapusLokasiLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(TFnomorlokasihapus, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PHapusLokasiLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel4)))
                .addContainerGap(274, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PHapusLokasiLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BHapusLokasi)
                .addGap(73, 73, 73))
        );
        PHapusLokasiLayout.setVerticalGroup(
            PHapusLokasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PHapusLokasiLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel4)
                .addGap(31, 31, 31)
                .addGroup(PHapusLokasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TFnomorlokasihapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(BHapusLokasi)
                .addContainerGap(200, Short.MAX_VALUE))
        );

        TPAdmin.addTab("Hapus Lokasi", PHapusLokasi);

        jLabel6.setText("TAMBAH KELOMPOK");

        jLabel7.setText("Pilih Lokasi");

        jLabel8.setText("Masukan ID Kelompok");

        BSimpanKelompok.setText("Simpan");

        jListLokasi.setToolTipText("");
        jListLokasi.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListLokasiValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jListLokasi);

        jLabel22.setText("Masukkan Urutan Lokasi");

        javax.swing.GroupLayout PTambahKelompokLayout = new javax.swing.GroupLayout(PTambahKelompok);
        PTambahKelompok.setLayout(PTambahKelompokLayout);
        PTambahKelompokLayout.setHorizontalGroup(
            PTambahKelompokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PTambahKelompokLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(PTambahKelompokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PTambahKelompokLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addContainerGap())
                    .addGroup(PTambahKelompokLayout.createSequentialGroup()
                        .addGroup(PTambahKelompokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(PTambahKelompokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PTambahKelompokLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BSimpanKelompok)
                                .addGap(48, 48, 48))
                            .addGroup(PTambahKelompokLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(PTambahKelompokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(PTambahKelompokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TFIdKelompoktambahklp, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                                    .addComponent(jTFUrutanL))
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        PTambahKelompokLayout.setVerticalGroup(
            PTambahKelompokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PTambahKelompokLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addGroup(PTambahKelompokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PTambahKelompokLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BSimpanKelompok)
                        .addGap(128, 128, 128))
                    .addGroup(PTambahKelompokLayout.createSequentialGroup()
                        .addGroup(PTambahKelompokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PTambahKelompokLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PTambahKelompokLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(PTambahKelompokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel22)
                                    .addComponent(jTFUrutanL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(50, 50, 50)
                                .addGroup(PTambahKelompokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(TFIdKelompoktambahklp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(45, 142, Short.MAX_VALUE))))
        );

        TPAdmin.addTab("Tambah Kelompok", PTambahKelompok);

        jLabel9.setText("HAPUS KELOMPOK");

        jLabel10.setText("Pilih Lokasi");

        jLabel11.setText("Masukan ID Kelompok");

        BHapusKelompok.setText("Hapus");

        javax.swing.GroupLayout PHapusKelompokLayout = new javax.swing.GroupLayout(PHapusKelompok);
        PHapusKelompok.setLayout(PHapusKelompokLayout);
        PHapusKelompokLayout.setHorizontalGroup(
            PHapusKelompokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PHapusKelompokLayout.createSequentialGroup()
                .addGroup(PHapusKelompokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PHapusKelompokLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel9)
                        .addGap(75, 75, 75))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PHapusKelompokLayout.createSequentialGroup()
                        .addGroup(PHapusKelompokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(PHapusKelompokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LLokasiKlphapuskelompok, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                    .addComponent(TFIdKlphapuskelompok))
                .addContainerGap(217, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PHapusKelompokLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BHapusKelompok)
                .addGap(77, 77, 77))
        );
        PHapusKelompokLayout.setVerticalGroup(
            PHapusKelompokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PHapusKelompokLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel9)
                .addGap(44, 44, 44)
                .addGroup(PHapusKelompokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(LLokasiKlphapuskelompok, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(PHapusKelompokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFIdKlphapuskelompok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(BHapusKelompok)
                .addContainerGap(145, Short.MAX_VALUE))
        );

        TPAdmin.addTab("Hapus Kelompok", PHapusKelompok);

        jLabel12.setText("HAPUS PEMBIMBING");

        jLabel13.setText("Pilih pembimbing");

        BHapusPembimbing.setText("Hapus");

        javax.swing.GroupLayout PHapusPembimbingLayout = new javax.swing.GroupLayout(PHapusPembimbing);
        PHapusPembimbing.setLayout(PHapusPembimbingLayout);
        PHapusPembimbingLayout.setHorizontalGroup(
            PHapusPembimbingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PHapusPembimbingLayout.createSequentialGroup()
                .addGroup(PHapusPembimbingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PHapusPembimbingLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel12))
                    .addGroup(PHapusPembimbingLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel13)
                        .addGap(19, 19, 19)
                        .addComponent(LpilihPembimbing, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(224, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PHapusPembimbingLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BHapusPembimbing)
                .addGap(87, 87, 87))
        );
        PHapusPembimbingLayout.setVerticalGroup(
            PHapusPembimbingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PHapusPembimbingLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel12)
                .addGap(38, 38, 38)
                .addGroup(PHapusPembimbingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(LpilihPembimbing, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(59, 59, 59)
                .addComponent(BHapusPembimbing)
                .addContainerGap(156, Short.MAX_VALUE))
        );

        TPAdmin.addTab("Hapus Pembimbing", PHapusPembimbing);

        jLabel14.setText("Nama Depan");

        TFNamadpnpembimbing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFNamadpnpembimbingActionPerformed(evt);
            }
        });

        jLabel15.setText("Nama Belakang");

        jLabel16.setText("Jenis Kelamin");

        RBLakipembimbing.setText("Laki-laki");

        RBPerempuanpembimbing.setText("Perempuan");

        CBTahunpembimbing.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001" }));

        CBBulanpembimbing.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));
        CBBulanpembimbing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBBulanpembimbingActionPerformed(evt);
            }
        });

        CBTanggalpembimbing.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        CBTanggalpembimbing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBTanggalpembimbingActionPerformed(evt);
            }
        });

        jLabel17.setText("Tanggal Lahir");

        jLabel18.setText("Nomor Telepon");

        jLabel19.setText("Alamat");

        jLabel21.setText("NIP");

        BSimpan2.setText("Simpan");

        jLabel20.setText("TAMBAH PEMBIMBING");

        javax.swing.GroupLayout PTambahPembimbingLayout = new javax.swing.GroupLayout(PTambahPembimbing);
        PTambahPembimbing.setLayout(PTambahPembimbingLayout);
        PTambahPembimbingLayout.setHorizontalGroup(
            PTambahPembimbingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PTambahPembimbingLayout.createSequentialGroup()
                .addGroup(PTambahPembimbingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PTambahPembimbingLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(TFNamadpnpembimbing, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PTambahPembimbingLayout.createSequentialGroup()
                        .addGroup(PTambahPembimbingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PTambahPembimbingLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(PTambahPembimbingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PTambahPembimbingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel20)
                                        .addComponent(jLabel21))
                                    .addGroup(PTambahPembimbingLayout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addComponent(jLabel19)))
                                .addGap(51, 51, 51))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PTambahPembimbingLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel18)
                                .addGap(18, 18, 18)))
                        .addGroup(PTambahPembimbingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PTambahPembimbingLayout.createSequentialGroup()
                                .addComponent(RBLakipembimbing)
                                .addGap(18, 18, 18)
                                .addComponent(RBPerempuanpembimbing))
                            .addGroup(PTambahPembimbingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TFAlamatpembimbing, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TFnippembimbing, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TFTeleponpembimbing, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PTambahPembimbingLayout.createSequentialGroup()
                                    .addComponent(CBTanggalpembimbing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(CBBulanpembimbing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(CBTahunpembimbing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(113, 113, 113)))
                            .addComponent(TFNamablkPembimbing, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(71, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PTambahPembimbingLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BSimpan2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
            .addGroup(PTambahPembimbingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PTambahPembimbingLayout.createSequentialGroup()
                    .addGap(38, 38, 38)
                    .addGroup(PTambahPembimbingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel15)
                        .addComponent(jLabel14)
                        .addComponent(jLabel17)
                        .addComponent(jLabel16))
                    .addContainerGap(426, Short.MAX_VALUE)))
        );
        PTambahPembimbingLayout.setVerticalGroup(
            PTambahPembimbingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PTambahPembimbingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addGap(3, 3, 3)
                .addComponent(TFNamadpnpembimbing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(TFNamablkPembimbing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PTambahPembimbingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RBLakipembimbing)
                    .addComponent(RBPerempuanpembimbing))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PTambahPembimbingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CBTanggalpembimbing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBBulanpembimbing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBTahunpembimbing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(PTambahPembimbingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFTeleponpembimbing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PTambahPembimbingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PTambahPembimbingLayout.createSequentialGroup()
                        .addComponent(TFAlamatpembimbing, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PTambahPembimbingLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(44, 44, 44)))
                .addGroup(PTambahPembimbingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFnippembimbing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BSimpan2)
                .addGap(29, 29, 29))
            .addGroup(PTambahPembimbingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PTambahPembimbingLayout.createSequentialGroup()
                    .addGap(36, 36, 36)
                    .addComponent(jLabel14)
                    .addGap(15, 15, 15)
                    .addComponent(jLabel15)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jLabel16)
                    .addGap(14, 14, 14)
                    .addComponent(jLabel17)
                    .addContainerGap(209, Short.MAX_VALUE)))
        );

        TPAdmin.addTab("Tambah Pembimbing", PTambahPembimbing);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TPAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TPAdmin, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TFNamadpnpembimbingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFNamadpnpembimbingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFNamadpnpembimbingActionPerformed

    private void CBBulanpembimbingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBBulanpembimbingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBBulanpembimbingActionPerformed

    private void CBTanggalpembimbingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBTanggalpembimbingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBTanggalpembimbingActionPerformed

    private void jListLokasiValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListLokasiValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jListLokasiValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAdmin().setVisible(true);
            }
        });
    }
    
    public void addListener(ActionListener n){
        BHapusKelompok.addActionListener(n);
        BHapusLokasi.addActionListener(n);
        BHapusPembimbing.addActionListener(n);
        BSimpan2.addActionListener(n);
        BSimpanKelompok.addActionListener(n);
        BSimpanLokasi.addActionListener(n);
    }
    public JButton getBHapusKelompok() {
        return BHapusKelompok;
    }

    public JButton getBHapusLokasi() {
        return BHapusLokasi;
    }

    public JButton getBHapusPembimbing() {
        return BHapusPembimbing;
    }

    public JButton getBSimpan2() {
        return BSimpan2;
    }

    public JButton getBSimpanKelompok() {
        return BSimpanKelompok;
    }

    public JButton getBSimpanLokasi() {
        return BSimpanLokasi;
    }

    public JComboBox<String> getCBBulanpembimbing() {
        return CBBulanpembimbing;
    }

    public JComboBox<String> getCBTahunpembimbing() {
        return CBTahunpembimbing;
    }

    public JComboBox<String> getCBTanggalpembimbing() {
        return CBTanggalpembimbing;
    }

    public List getLLokasiKlphapuskelompok() {
        return LLokasiKlphapuskelompok;
    }


    public List getLpilihPembimbing() {
        return LpilihPembimbing;
    }

    public JPanel getPHapusKelompok() {
        return PHapusKelompok;
    }

    public JPanel getPHapusLokasi() {
        return PHapusLokasi;
    }

    public JPanel getPHapusPembimbing() {
        return PHapusPembimbing;
    }

    public JPanel getPTambahKelompok() {
        return PTambahKelompok;
    }

    public JPanel getPTambahLokasi() {
        return PTambahLokasi;
    }

    public JPanel getPTambahPembimbing() {
        return PTambahPembimbing;
    }

    public JRadioButton getRBLakipembimbing() {
        return RBLakipembimbing;
    }

    public JRadioButton getRBPerempuanpembimbing() {
        return RBPerempuanpembimbing;
    }

    public JTextField getTFAlamatpembimbing() {
        return TFAlamatpembimbing;
    }

    public JTextField getTFIdKelompoktambahklp() {
        return TFIdKelompoktambahklp;
    }

    public JTextField getTFIdKlphapuskelompok() {
        return TFIdKlphapuskelompok;
    }

    public JTextField getTFNamablkPembimbing() {
        return TFNamablkPembimbing;
    }

    public JTextField getTFNamadpnpembimbing() {
        return TFNamadpnpembimbing;
    }

    public JTextField getTFTeleponpembimbing() {
        return TFTeleponpembimbing;
    }

    public JTextField getTFnippembimbing() {
        return TFnippembimbing;
    }

    public JTextField getTFnomorLokasi() {
        return TFnomorLokasi;
    }

    public JTextField getTFnomorlokasihapus() {
        return TFnomorlokasihapus;
    }

    public JTextField getTFtambahnamalokasi() {
        return TFtambahnamalokasi;
    }

    public JTabbedPane getTPAdmin() {
        return TPAdmin;
    }
    public Date BirthAdmin(){
       Date b = new Date();
       b.setDate(CBTanggalpembimbing.getSelectedIndex()+1);
       b.setMonth(CBBulanpembimbing.getSelectedIndex()+1);
       b.setYear(CBTahunpembimbing.getSelectedIndex()+89);
       return b;
    }
    public void resetIL(){
        TFtambahnamalokasi.setText("");
        TFnomorLokasi.setText("");
    }

    public JList<String> getjListLokasi() {
        return jListLokasi;
    }

    public JTextField getjTFUrutanL() {
        return jTFUrutanL;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BHapusKelompok;
    private javax.swing.JButton BHapusLokasi;
    private javax.swing.JButton BHapusPembimbing;
    private javax.swing.JButton BSimpan2;
    private javax.swing.JButton BSimpanKelompok;
    private javax.swing.JButton BSimpanLokasi;
    private javax.swing.JComboBox<String> CBBulanpembimbing;
    private javax.swing.JComboBox<String> CBTahunpembimbing;
    private javax.swing.JComboBox<String> CBTanggalpembimbing;
    private java.awt.List LLokasiKlphapuskelompok;
    private java.awt.List LpilihPembimbing;
    private javax.swing.JPanel PHapusKelompok;
    private javax.swing.JPanel PHapusLokasi;
    private javax.swing.JPanel PHapusPembimbing;
    private javax.swing.JPanel PTambahKelompok;
    private javax.swing.JPanel PTambahLokasi;
    private javax.swing.JPanel PTambahPembimbing;
    private javax.swing.JRadioButton RBLakipembimbing;
    private javax.swing.JRadioButton RBPerempuanpembimbing;
    private javax.swing.JTextField TFAlamatpembimbing;
    private javax.swing.JTextField TFIdKelompoktambahklp;
    private javax.swing.JTextField TFIdKlphapuskelompok;
    private javax.swing.JTextField TFNamablkPembimbing;
    private javax.swing.JTextField TFNamadpnpembimbing;
    private javax.swing.JTextField TFTeleponpembimbing;
    private javax.swing.JTextField TFnippembimbing;
    private javax.swing.JTextField TFnomorLokasi;
    private javax.swing.JTextField TFnomorlokasihapus;
    private javax.swing.JTextField TFtambahnamalokasi;
    private javax.swing.JTabbedPane TPAdmin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jListLokasi;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFUrutanL;
    // End of variables declaration//GEN-END:variables
}
