/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.List;
import java.awt.event.ActionListener;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTabbedPane;
import javax.swing.JTextField;

/**
 *
 * @author rannypa
 */
public class MenuAdmin extends javax.swing.JFrame {

    /**
     * Creates new form MenuAdmin
     */
    public MenuAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        TPAdmin = new javax.swing.JTabbedPane();
        PHapusLokasi = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TFnamalokasihapus = new javax.swing.JTextField();
        BHapusLokasi = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListHLok = new javax.swing.JList<>();
        BKeluarHapusLokasi = new javax.swing.JButton();
        PTambahKelompok = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TFIdKelompoktambahklp = new javax.swing.JTextField();
        BSimpanKelompok = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListLokasi = new javax.swing.JList<>();
        jLabel22 = new javax.swing.JLabel();
        jTFUnmL = new javax.swing.JTextField();
        BKeluarTambahKelompok = new javax.swing.JButton();
        PHapusKelompok = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        BHapusKelompok = new javax.swing.JButton();
        TFIdKlphapuskelompok = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListHK = new javax.swing.JList<>();
        jTFPLHL = new javax.swing.JTextField();
        BKeluarHapusKelompok = new javax.swing.JButton();
        PHapusPembimbing = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        BHapusPembimbing = new javax.swing.JButton();
        jTextFieldPP = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jListHP = new javax.swing.JList<>();
        BKeluarHapusPembimbing = new javax.swing.JButton();
        PTambahPembimbing = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        TFNamadpnpembimbing = new javax.swing.JTextField();
        TFNamablkPembimbing = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        RBLakipembimbing = new javax.swing.JRadioButton();
        RBPerempuanpembimbing = new javax.swing.JRadioButton();
        CBTahunpembimbing = new javax.swing.JComboBox<>();
        CBBulanpembimbing = new javax.swing.JComboBox<>();
        CBTanggalpembimbing = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        TFTeleponpembimbing = new javax.swing.JTextField();
        TFAlamatpembimbing = new javax.swing.JTextField();
        TFnippembimbing = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        BSimpan2 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        JTFNL = new javax.swing.JTextField();
        BKeluarTambahPembimbing = new javax.swing.JButton();
        PTambahLokasi = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TFtambahnamalokasi = new javax.swing.JTextField();
        TFnomorLokasi = new javax.swing.JTextField();
        BSimpanLokasi = new javax.swing.JButton();
        BKeluarTambahLokasi = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        BHapusPembimbing1 = new javax.swing.JButton();
        jTextFieldNimPeserta = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jListHpsPeserta = new javax.swing.JList<>();
        jLabel25 = new javax.swing.JLabel();
        BKeluarHapusPeserta = new javax.swing.JButton();
        jTFKelompokHP = new javax.swing.JTextField();
        jTFLokasiHP = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jButtonPilih = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PHapusLokasi.setBackground(new java.awt.Color(102, 102, 102));

        jLabel4.setFont(new java.awt.Font("Soup of Justice", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("HAPUS LOKASI");

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Masukan Nama Lokasi");

        TFnamalokasihapus.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N

        BHapusLokasi.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        BHapusLokasi.setText("Hapus");

        jScrollPane3.setViewportView(jListHLok);

        BKeluarHapusLokasi.setText("Keluar");

        javax.swing.GroupLayout PHapusLokasiLayout = new javax.swing.GroupLayout(PHapusLokasi);
        PHapusLokasi.setLayout(PHapusLokasiLayout);
        PHapusLokasiLayout.setHorizontalGroup(
            PHapusLokasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PHapusLokasiLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(PHapusLokasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PHapusLokasiLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PHapusLokasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PHapusLokasiLayout.createSequentialGroup()
                                .addComponent(TFnamalokasihapus, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(BHapusLokasi))
                            .addComponent(jLabel5))
                        .addContainerGap(201, Short.MAX_VALUE))
                    .addGroup(PHapusLokasiLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BKeluarHapusLokasi)
                        .addGap(53, 53, 53))))
        );
        PHapusLokasiLayout.setVerticalGroup(
            PHapusLokasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PHapusLokasiLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(PHapusLokasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(BKeluarHapusLokasi))
                .addGap(18, 18, 18)
                .addGroup(PHapusLokasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PHapusLokasiLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PHapusLokasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TFnamalokasihapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BHapusLokasi)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(249, Short.MAX_VALUE))
        );

        TPAdmin.addTab("Hapus Lokasi", PHapusLokasi);

        PTambahKelompok.setBackground(new java.awt.Color(102, 102, 102));

        jLabel6.setFont(new java.awt.Font("Soup of Justice", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("TAMBAH KELOMPOK");

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Pilih Lokasi");

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Masukan ID Kelompok");

        TFIdKelompoktambahklp.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N

        BSimpanKelompok.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        BSimpanKelompok.setText("Simpan");

        jListLokasi.setToolTipText("");
        jListLokasi.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListLokasiValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jListLokasi);

        jLabel22.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Masukkan Nama Lokasi");

        jTFUnmL.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N

        BKeluarTambahKelompok.setText("Keluar");

        javax.swing.GroupLayout PTambahKelompokLayout = new javax.swing.GroupLayout(PTambahKelompok);
        PTambahKelompok.setLayout(PTambahKelompokLayout);
        PTambahKelompokLayout.setHorizontalGroup(
            PTambahKelompokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PTambahKelompokLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(PTambahKelompokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PTambahKelompokLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(PTambahKelompokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PTambahKelompokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(PTambahKelompokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TFIdKelompoktambahklp, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFUnmL, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 119, Short.MAX_VALUE))
                    .addGroup(PTambahKelompokLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BKeluarTambahKelompok)
                        .addGap(37, 37, 37))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PTambahKelompokLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BSimpanKelompok)
                .addGap(45, 45, 45))
        );
        PTambahKelompokLayout.setVerticalGroup(
            PTambahKelompokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PTambahKelompokLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(PTambahKelompokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(BKeluarTambahKelompok))
                .addGap(22, 22, 22)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PTambahKelompokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PTambahKelompokLayout.createSequentialGroup()
                        .addGroup(PTambahKelompokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(jTFUnmL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PTambahKelompokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(TFIdKelompoktambahklp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BSimpanKelompok))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(222, Short.MAX_VALUE))
        );

        TPAdmin.addTab("Tambah Kelompok", PTambahKelompok);

        PHapusKelompok.setBackground(new java.awt.Color(102, 102, 102));

        jLabel9.setFont(new java.awt.Font("Soup of Justice", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("HAPUS KELOMPOK");

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Pilih Lokasi");

        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Masukan ID Kelompok");

        BHapusKelompok.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        BHapusKelompok.setText("Hapus");

        TFIdKlphapuskelompok.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        TFIdKlphapuskelompok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFIdKlphapuskelompokActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(jListHK);

        jTFPLHL.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N

        BKeluarHapusKelompok.setText("Keluar");

        javax.swing.GroupLayout PHapusKelompokLayout = new javax.swing.GroupLayout(PHapusKelompok);
        PHapusKelompok.setLayout(PHapusKelompokLayout);
        PHapusKelompokLayout.setHorizontalGroup(
            PHapusKelompokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PHapusKelompokLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(PHapusKelompokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PHapusKelompokLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PHapusKelompokLayout.createSequentialGroup()
                        .addGroup(PHapusKelompokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(PHapusKelompokLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(22, 22, 22))
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)))
                .addGroup(PHapusKelompokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PHapusKelompokLayout.createSequentialGroup()
                        .addGroup(PHapusKelompokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TFIdKlphapuskelompok, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFPLHL, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BHapusKelompok)
                        .addContainerGap(58, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PHapusKelompokLayout.createSequentialGroup()
                        .addComponent(BKeluarHapusKelompok)
                        .addGap(35, 35, 35))))
        );
        PHapusKelompokLayout.setVerticalGroup(
            PHapusKelompokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PHapusKelompokLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(PHapusKelompokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(BKeluarHapusKelompok))
                .addGap(3, 3, 3)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PHapusKelompokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFPLHL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(PHapusKelompokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFIdKlphapuskelompok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BHapusKelompok))
                .addContainerGap(210, Short.MAX_VALUE))
        );

        TPAdmin.addTab("Hapus Kelompok", PHapusKelompok);

        PHapusPembimbing.setBackground(new java.awt.Color(102, 102, 102));

        jLabel12.setFont(new java.awt.Font("Soup of Justice", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("HAPUS PEMBIMBING");

        jLabel13.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Masukkan NIP Pembimbing");

        BHapusPembimbing.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        BHapusPembimbing.setText("Hapus");

        jTextFieldPP.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jTextFieldPP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPPActionPerformed(evt);
            }
        });

        jScrollPane4.setViewportView(jListHP);

        BKeluarHapusPembimbing.setText("Keluar");

        javax.swing.GroupLayout PHapusPembimbingLayout = new javax.swing.GroupLayout(PHapusPembimbing);
        PHapusPembimbing.setLayout(PHapusPembimbingLayout);
        PHapusPembimbingLayout.setHorizontalGroup(
            PHapusPembimbingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PHapusPembimbingLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(PHapusPembimbingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PHapusPembimbingLayout.createSequentialGroup()
                        .addGroup(PHapusPembimbingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PHapusPembimbingLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(51, 51, 51)
                                .addComponent(jTextFieldPP, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70)
                                .addComponent(BHapusPembimbing))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(83, Short.MAX_VALUE))
                    .addGroup(PHapusPembimbingLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BKeluarHapusPembimbing)
                        .addGap(30, 30, 30))))
        );
        PHapusPembimbingLayout.setVerticalGroup(
            PHapusPembimbingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PHapusPembimbingLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(PHapusPembimbingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(BKeluarHapusPembimbing))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addGroup(PHapusPembimbingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BHapusPembimbing))
                .addGap(146, 146, 146))
        );

        TPAdmin.addTab("Hapus Pembimbing", PHapusPembimbing);

        PTambahPembimbing.setBackground(new java.awt.Color(102, 102, 102));

        jLabel14.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Nama Depan");

        TFNamadpnpembimbing.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        TFNamadpnpembimbing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFNamadpnpembimbingActionPerformed(evt);
            }
        });

        TFNamablkPembimbing.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Nama Belakang");

        jLabel16.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Jenis Kelamin");

        RBLakipembimbing.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        RBLakipembimbing.setText("Laki-laki");

        RBPerempuanpembimbing.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        RBPerempuanpembimbing.setText("Perempuan");

        CBTahunpembimbing.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        CBTahunpembimbing.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001" }));

        CBBulanpembimbing.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        CBBulanpembimbing.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));
        CBBulanpembimbing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBBulanpembimbingActionPerformed(evt);
            }
        });

        CBTanggalpembimbing.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        CBTanggalpembimbing.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        CBTanggalpembimbing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBTanggalpembimbingActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Tanggal Lahir");

        jLabel18.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Nomor Telepon");

        jLabel19.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Alamat");

        TFTeleponpembimbing.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N

        TFAlamatpembimbing.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N

        TFnippembimbing.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N

        jLabel21.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("NIP");

        BSimpan2.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        BSimpan2.setText("Simpan");

        jLabel20.setFont(new java.awt.Font("Soup of Justice", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("TAMBAH PEMBIMBING");

        jLabel23.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Nama Lokasi");

        JTFNL.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        JTFNL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFNLActionPerformed(evt);
            }
        });

        BKeluarTambahPembimbing.setText("Keluar");

        javax.swing.GroupLayout PTambahPembimbingLayout = new javax.swing.GroupLayout(PTambahPembimbing);
        PTambahPembimbing.setLayout(PTambahPembimbingLayout);
        PTambahPembimbingLayout.setHorizontalGroup(
            PTambahPembimbingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PTambahPembimbingLayout.createSequentialGroup()
                .addGroup(PTambahPembimbingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PTambahPembimbingLayout.createSequentialGroup()
                        .addGap(437, 437, 437)
                        .addComponent(BSimpan2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))
                    .addGroup(PTambahPembimbingLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(PTambahPembimbingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PTambahPembimbingLayout.createSequentialGroup()
                                .addGroup(PTambahPembimbingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PTambahPembimbingLayout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PTambahPembimbingLayout.createSequentialGroup()
                                        .addGroup(PTambahPembimbingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel15)
                                            .addComponent(jLabel16)
                                            .addComponent(jLabel14))
                                        .addGap(18, 18, 18)))
                                .addGroup(PTambahPembimbingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PTambahPembimbingLayout.createSequentialGroup()
                                        .addComponent(RBLakipembimbing)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(RBPerempuanpembimbing))
                                    .addComponent(TFNamablkPembimbing, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(PTambahPembimbingLayout.createSequentialGroup()
                                        .addComponent(CBTanggalpembimbing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(CBBulanpembimbing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(CBTahunpembimbing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(TFNamadpnpembimbing, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(PTambahPembimbingLayout.createSequentialGroup()
                                .addGroup(PTambahPembimbingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel23))
                                .addGap(18, 18, 18)
                                .addGroup(PTambahPembimbingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TFAlamatpembimbing, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TFTeleponpembimbing, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(PTambahPembimbingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(JTFNL, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(TFnippembimbing, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(PTambahPembimbingLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BKeluarTambahPembimbing)))
                .addGap(29, 29, 29))
        );
        PTambahPembimbingLayout.setVerticalGroup(
            PTambahPembimbingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PTambahPembimbingLayout.createSequentialGroup()
                .addGroup(PTambahPembimbingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PTambahPembimbingLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel20)
                        .addGroup(PTambahPembimbingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PTambahPembimbingLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(PTambahPembimbingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TFNamadpnpembimbing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TFNamablkPembimbing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(PTambahPembimbingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(RBLakipembimbing)
                                    .addComponent(RBPerempuanpembimbing))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(PTambahPembimbingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(CBTanggalpembimbing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CBBulanpembimbing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CBTahunpembimbing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(PTambahPembimbingLayout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel16)
                                .addGap(14, 14, 14)
                                .addComponent(jLabel17))))
                    .addGroup(PTambahPembimbingLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(BKeluarTambahPembimbing)))
                .addGap(18, 18, 18)
                .addGroup(PTambahPembimbingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFTeleponpembimbing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(PTambahPembimbingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFAlamatpembimbing, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PTambahPembimbingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFnippembimbing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PTambahPembimbingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(JTFNL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(BSimpan2)
                .addGap(32, 32, 32))
        );

        TPAdmin.addTab("Tambah Pembimbing", PTambahPembimbing);

        PTambahLokasi.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Soup of Justice", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TAMBAH LOKASI");

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nama Lokasi");

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nomor Lokasi ");

        TFtambahnamalokasi.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N

        TFnomorLokasi.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N

        BSimpanLokasi.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        BSimpanLokasi.setText("Simpan");

        BKeluarTambahLokasi.setText("Keluar");

        javax.swing.GroupLayout PTambahLokasiLayout = new javax.swing.GroupLayout(PTambahLokasi);
        PTambahLokasi.setLayout(PTambahLokasiLayout);
        PTambahLokasiLayout.setHorizontalGroup(
            PTambahLokasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PTambahLokasiLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(PTambahLokasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(PTambahLokasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TFtambahnamalokasi, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                    .addComponent(TFnomorLokasi))
                .addContainerGap(298, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PTambahLokasiLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BSimpanLokasi)
                .addGap(57, 57, 57))
            .addGroup(PTambahLokasiLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BKeluarTambahLokasi)
                .addGap(30, 30, 30))
        );
        PTambahLokasiLayout.setVerticalGroup(
            PTambahLokasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PTambahLokasiLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(PTambahLokasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(BKeluarTambahLokasi))
                .addGap(26, 26, 26)
                .addGroup(PTambahLokasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TFtambahnamalokasi, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PTambahLokasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TFnomorLokasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addComponent(BSimpanLokasi)
                .addContainerGap(228, Short.MAX_VALUE))
        );

        TPAdmin.addTab("Tambah Lokasi", PTambahLokasi);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        BHapusPembimbing1.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        BHapusPembimbing1.setText("Hapus");
        BHapusPembimbing1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BHapusPembimbing1ActionPerformed(evt);
            }
        });

        jTextFieldNimPeserta.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jTextFieldNimPeserta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNimPesertaActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Masukkan NIM Peserta");

        jScrollPane5.setViewportView(jListHpsPeserta);

        jLabel25.setFont(new java.awt.Font("Soup of Justice", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("HAPUS PEserta");

        BKeluarHapusPeserta.setText("Keluar");

        jLabel26.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Masukkan ID Kelompok ");

        jLabel27.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Masukkan Nama Lokasi");

        jButtonPilih.setText("Pilih");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel26)
                                    .addComponent(jLabel27))
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BHapusPembimbing1)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTFLokasiHP)
                                            .addComponent(jTFKelompokHP)
                                            .addComponent(jTextFieldNimPeserta, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonPilih)))))
                        .addContainerGap(180, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BKeluarHapusPeserta)
                        .addGap(30, 30, 30))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel25)
                    .addComponent(BKeluarHapusPeserta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTFLokasiHP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFKelompokHP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonPilih))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNimPeserta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(BHapusPembimbing1))
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(103, 103, 103))
        );

        TPAdmin.addTab("Hapus Peserta", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TPAdmin)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TPAdmin, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TFNamadpnpembimbingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFNamadpnpembimbingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFNamadpnpembimbingActionPerformed

    private void CBBulanpembimbingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBBulanpembimbingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBBulanpembimbingActionPerformed

    private void CBTanggalpembimbingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBTanggalpembimbingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBTanggalpembimbingActionPerformed

    private void jListLokasiValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListLokasiValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jListLokasiValueChanged

    private void JTFNLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFNLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFNLActionPerformed

    private void jTextFieldPPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPPActionPerformed

    private void TFIdKlphapuskelompokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFIdKlphapuskelompokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFIdKlphapuskelompokActionPerformed

    private void jTextFieldNimPesertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNimPesertaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNimPesertaActionPerformed

    private void BHapusPembimbing1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BHapusPembimbing1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BHapusPembimbing1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAdmin().setVisible(true);
            }
        });
    }
    
    public void addListener(ActionListener n){
        BHapusKelompok.addActionListener(n);
        BHapusLokasi.addActionListener(n);
        BHapusPembimbing.addActionListener(n);
        BSimpan2.addActionListener(n);
        BSimpanKelompok.addActionListener(n);
        BSimpanLokasi.addActionListener(n);
        BKeluarHapusKelompok.addActionListener(n);
        BKeluarHapusLokasi.addActionListener(n);
        BKeluarHapusPembimbing.addActionListener(n);
        BKeluarTambahKelompok.addActionListener(n);
        BKeluarTambahLokasi.addActionListener(n);
        BKeluarTambahPembimbing.addActionListener(n);
        BKeluarHapusPeserta.addActionListener(n);
        
    }
    public JButton getBHapusKelompok() {
        return BHapusKelompok;
    }

    public JButton getBHapusLokasi() {
        return BHapusLokasi;
    }

    public JButton getBHapusPembimbing() {
        return BHapusPembimbing;
    }

    public JButton getBSimpan2() {
        return BSimpan2;
    }

    public JButton getBSimpanKelompok() {
        return BSimpanKelompok;
    }

    public JButton getBSimpanLokasi() {
        return BSimpanLokasi;
    }

    public JComboBox<String> getCBBulanpembimbing() {
        return CBBulanpembimbing;
    }

    public JComboBox<String> getCBTahunpembimbing() {
        return CBTahunpembimbing;
    }

    public JComboBox<String> getCBTanggalpembimbing() {
        return CBTanggalpembimbing;
    }

    public JTextField getjTextFieldPP() {
        return jTextFieldPP;
    }

    


    

    public JPanel getPHapusKelompok() {
        return PHapusKelompok;
    }

    public JPanel getPHapusLokasi() {
        return PHapusLokasi;
    }

    public JPanel getPHapusPembimbing() {
        return PHapusPembimbing;
    }

    public JPanel getPTambahKelompok() {
        return PTambahKelompok;
    }

    public JPanel getPTambahLokasi() {
        return PTambahLokasi;
    }

    public JPanel getPTambahPembimbing() {
        return PTambahPembimbing;
    }

    public JRadioButton getRBLakipembimbing() {
        return RBLakipembimbing;
    }

    public JRadioButton getRBPerempuanpembimbing() {
        return RBPerempuanpembimbing;
    }

    public JTextField getTFAlamatpembimbing() {
        return TFAlamatpembimbing;
    }

    public JTextField getTFIdKelompoktambahklp() {
        return TFIdKelompoktambahklp;
    }

    public JTextField getTFIdKlphapuskelompok() {
        return TFIdKlphapuskelompok;
    }

    public JTextField getTFNamablkPembimbing() {
        return TFNamablkPembimbing;
    }

    public JTextField getTFNamadpnpembimbing() {
        return TFNamadpnpembimbing;
    }

    public JTextField getTFTeleponpembimbing() {
        return TFTeleponpembimbing;
    }

    public JTextField getTFnippembimbing() {
        return TFnippembimbing;
    }

    public JTextField getTFnomorLokasi() {
        return TFnomorLokasi;
    }

    public JTextField getTFnamalokasihapus() {
        return TFnamalokasihapus;
    }

    public JTextField getTFtambahnamalokasi() {
        return TFtambahnamalokasi;
    }

    public JTabbedPane getTPAdmin() {
        return TPAdmin;
    }

    public JButton getBKeluarHapusKelompok() {
        return BKeluarHapusKelompok;
    }

    public JButton getBKeluarHapusLokasi() {
        return BKeluarHapusLokasi;
    }

    public JButton getBKeluarHapusPembimbing() {
        return BKeluarHapusPembimbing;
    }

    public JButton getBKeluarTambahKelompok() {
        return BKeluarTambahKelompok;
    }

    public JButton getBKeluarTambahLokasi() {
        return BKeluarTambahLokasi;
    }

    public JButton getBKeluarTambahPembimbing() {
        return BKeluarTambahPembimbing;
    }

    public JButton getBHapusPembimbing1() {
        return BHapusPembimbing1;
    }

    public JButton getBKeluarHapusPeserta() {
        return BKeluarHapusPeserta;
    }

    public JList<String> getjListHpsPeserta() {
        return jListHpsPeserta;
    }

    public JTextField getjTextFieldNimPeserta() {
        return jTextFieldNimPeserta;
    }
    
    
    public Date BirthAdmin(){
       Date b = new Date();
       b.setDate(CBTanggalpembimbing.getSelectedIndex()+1);
       b.setMonth(CBBulanpembimbing.getSelectedIndex()+1);
       b.setYear(CBTahunpembimbing.getSelectedIndex()+89);
       return b;
    }
    public void resetIL(){
        TFtambahnamalokasi.setText("");
        TFnomorLokasi.setText("");
    }

    public JList<String> getjListLokasi() {
        return jListLokasi;
    }

    public JTextField getjTFUrutanL() {
        return jTFUnmL;
    }
    public void resetTK(){
        jTFUnmL.setText("");
        TFIdKelompoktambahklp.setText("");
    }

    public JList<String> getjListHK() {
        return jListHK;
    }

    public JTextField getjTFPLHL() {
        return jTFPLHL;
    }

    public JTextField getjTFUnmL() {
        return jTFUnmL;
    }
    public void resetHP(){
        jTFPLHL.setText("");
        TFIdKlphapuskelompok.setText("");
    }
    public void resetHLok(){
        TFnamalokasihapus.setText("");
    }

    public JList<String> getjListHLok() {
        return jListHLok;
    }
    public Date getBirth(){
        Date b = new Date();
        b.setDate(CBTanggalpembimbing.getSelectedIndex()+1);
        b.setMonth(CBBulanpembimbing.getSelectedIndex()+1);
        b.setYear(CBTahunpembimbing.getSelectedIndex()+1989);
        return b;
    }

    public JTextField getJTFNL() {
        return JTFNL;
    }

    public JList<String> getjListHP() {
        return jListHP;
    }
    public void resetHP2(){
        jTextFieldPP.setText("");
    }
    public void rTambahP(){
        TFNamadpnpembimbing.setText("");
        TFNamablkPembimbing.setText("");
        TFAlamatpembimbing.setText("");
        TFTeleponpembimbing.setText("");
        TFnippembimbing.setText("");
        JTFNL.setText("");
    }
    
    
    
    
    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BHapusKelompok;
    private javax.swing.JButton BHapusLokasi;
    private javax.swing.JButton BHapusPembimbing;
    private javax.swing.JButton BHapusPembimbing1;
    private javax.swing.JButton BKeluarHapusKelompok;
    private javax.swing.JButton BKeluarHapusLokasi;
    private javax.swing.JButton BKeluarHapusPembimbing;
    private javax.swing.JButton BKeluarHapusPeserta;
    private javax.swing.JButton BKeluarTambahKelompok;
    private javax.swing.JButton BKeluarTambahLokasi;
    private javax.swing.JButton BKeluarTambahPembimbing;
    private javax.swing.JButton BSimpan2;
    private javax.swing.JButton BSimpanKelompok;
    private javax.swing.JButton BSimpanLokasi;
    private javax.swing.JComboBox<String> CBBulanpembimbing;
    private javax.swing.JComboBox<String> CBTahunpembimbing;
    private javax.swing.JComboBox<String> CBTanggalpembimbing;
    private javax.swing.JTextField JTFNL;
    private javax.swing.JPanel PHapusKelompok;
    private javax.swing.JPanel PHapusLokasi;
    private javax.swing.JPanel PHapusPembimbing;
    private javax.swing.JPanel PTambahKelompok;
    private javax.swing.JPanel PTambahLokasi;
    private javax.swing.JPanel PTambahPembimbing;
    private javax.swing.JRadioButton RBLakipembimbing;
    private javax.swing.JRadioButton RBPerempuanpembimbing;
    private javax.swing.JTextField TFAlamatpembimbing;
    private javax.swing.JTextField TFIdKelompoktambahklp;
    private javax.swing.JTextField TFIdKlphapuskelompok;
    private javax.swing.JTextField TFNamablkPembimbing;
    private javax.swing.JTextField TFNamadpnpembimbing;
    private javax.swing.JTextField TFTeleponpembimbing;
    private javax.swing.JTextField TFnamalokasihapus;
    private javax.swing.JTextField TFnippembimbing;
    private javax.swing.JTextField TFnomorLokasi;
    private javax.swing.JTextField TFtambahnamalokasi;
    private javax.swing.JTabbedPane TPAdmin;
    private javax.swing.JButton jButtonPilih;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jListHK;
    private javax.swing.JList<String> jListHLok;
    private javax.swing.JList<String> jListHP;
    private javax.swing.JList<String> jListHpsPeserta;
    private javax.swing.JList<String> jListLokasi;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTFKelompokHP;
    private javax.swing.JTextField jTFLokasiHP;
    private javax.swing.JTextField jTFPLHL;
    private javax.swing.JTextField jTFUnmL;
    private javax.swing.JTextField jTextFieldNimPeserta;
    private javax.swing.JTextField jTextFieldPP;
    // End of variables declaration//GEN-END:variables
}
